FROM docker.elastic.co/beats/filebeat:8.12.0
COPY --chown=root:root filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN chmod 600 /usr/share/filebeat/filebeat.yml && \
    chown root:root /usr/share/filebeat/filebeat.yml
USER filebeat